# Generated by Django 3.0.8 on 2020-10-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.CharField(max_length=10)),
                ('highest_qualification', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('self-employed', 'self-employed')], default='', max_length=20)),
            ],
        ),
    ]
