# Generated by Django 3.0.8 on 2020-10-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
